import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth } from './AuthContext';
import { useToast } from '@/hooks/use-toast';

interface WishlistItem {
  id: string;
  product: {
    id: number;
    name: string;
    price: number;
    originalPrice?: number;
    image: string;
    category: string;
    rating: number;
    isOnSale?: boolean;
    discount?: number;
    stock: number;
  };
  addedAt: Date;
}

interface WishlistContextType {
  wishlistItems: WishlistItem[];
  isLoading: boolean;
  addToWishlist: (product: any) => Promise<void>;
  removeFromWishlist: (itemId: string) => Promise<void>;
  isInWishlist: (productId: number) => boolean;
  clearWishlist: () => Promise<void>;
  refreshWishlist: () => Promise<void>;
}

const WishlistContext = createContext<WishlistContextType | undefined>(undefined);

export const useWishlist = () => {
  const context = useContext(WishlistContext);
  if (context === undefined) {
    throw new Error('useWishlist must be used within a WishlistProvider');
  }
  return context;
};

interface WishlistProviderProps {
  children: ReactNode;
}

export const WishlistProvider: React.FC<WishlistProviderProps> = ({ children }) => {
  const [wishlistItems, setWishlistItems] = useState<WishlistItem[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { user, token } = useAuth();
  const { toast } = useToast();

  const API_BASE_URL = 'http://localhost:5000/api';

  // Product ID mapping for demo products to MongoDB ObjectIds
  // This mapping will be updated when we fetch real products from the backend
  const [productIdMapping, setProductIdMapping] = useState<Record<number, string>>({
    // Real product IDs from database (generated by seeding script)
    1: "68894b07c48ce012657b2617", // Fresh Avocados
    2: "68894b07c48ce012657b261a", // Premium Coffee Beans
    3: "68894b07c48ce012657b261d", // Organic Honey
    4: "68894b08c48ce012657b2620", // Fresh Fish Selection
    5: "68894b08c48ce012657b2623", // Local Palm Oil
    6: "68894b08c48ce012657b2626", // Imported Wine
    7: "68894b08c48ce012657b2629", // Fresh Pineapple
    8: "68894b08c48ce012657b262c"  // Imported Cheese
  });

  // Create reverse mapping from MongoDB ObjectIds to frontend numeric IDs
  const getReverseMapping = () => {
    const reverseMapping: Record<string, number> = {};
    Object.entries(productIdMapping).forEach(([frontendId, mongoId]) => {
      reverseMapping[mongoId] = parseInt(frontendId);
    });
    return reverseMapping;
  };

  // Fetch products to get the mapping of demo IDs to MongoDB ObjectIds
  const fetchProductMapping = async () => {
    // Don't fetch if user is not authenticated
    if (!user || !token) {
      return;
    }

    try {
      const response = await fetch(`${API_BASE_URL}/products`);
      if (response.ok) {
        const data = await response.json();
        const mapping: Record<number, string> = {};
        
        // Check if data.data.products exists and is an array
        if (!data.data || !data.data.products || !Array.isArray(data.data.products)) {
          console.error('Invalid products data structure:', data);
          return;
        }
        
        // Create mapping based on product names (since demo products have specific names)
        data.data.products.forEach((product: any, index: number) => {
          if (product && product._id) {
            const demoId = index + 1; // Demo products are numbered 1, 2, 3, etc.
            mapping[demoId] = product._id;
          }
        });
        
        setProductIdMapping(mapping);
      }
    } catch (error) {
      console.error('Error fetching product mapping:', error);
      // Don't throw the error, just log it
    }
  };

  // Demo wishlist data for testing
  const demoWishlistItems: WishlistItem[] = [
    {
      id: '1',
      product: {
        id: 1,
        name: 'Fresh Avocados',
        price: 2500,
        originalPrice: 3000,
        image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=300&h=300&fit=crop',
        category: 'Fresh Fruits',
        rating: 4.8,
        isOnSale: true,
        discount: 17,
        stock: 50
      },
      addedAt: new Date('2024-01-15')
    },
    {
      id: '2',
      product: {
        id: 2,
        name: 'Premium Coffee Beans',
        price: 8500,
        image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&h=300&fit=crop',
        category: 'Beverages',
        rating: 4.9,
        isOnSale: false,
        stock: 30
      },
      addedAt: new Date('2024-01-14')
    },
    {
      id: '3',
      product: {
        id: 6,
        name: 'Imported Wine',
        price: 12000,
        originalPrice: 15000,
        image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=300&h=300&fit=crop',
        category: 'Alcoholic Beverages',
        rating: 4.5,
        isOnSale: true,
        discount: 20,
        stock: 15
      },
      addedAt: new Date('2024-01-13')
    }
  ];

  // Fetch wishlist from backend
  const fetchWishlist = async () => {
    if (!user || !token) {
      setWishlistItems([]);
      return;
    }

    try {
      setIsLoading(true);
      const response = await fetch(`${API_BASE_URL}/wishlist`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const data = await response.json();
        
        // Check if data.data.items exists and is an array
        if (!data.data || !data.data.items || !Array.isArray(data.data.items)) {
          console.error('Invalid wishlist data structure:', data);
          setWishlistItems([]);
          return;
        }
        
        // Transform backend data to frontend format
        const transformedItems = data.data.items.map((item: any) => {
          const reverseMapping = getReverseMapping();
          const frontendId = reverseMapping[item.product._id];

          return {
            id: item._id,
            product: {
              id: frontendId, // Use the frontend ID
              name: item.product.name,
              price: item.product.price,
              originalPrice: item.product.originalPrice,
              image: item.product.images?.[0]?.url || 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=300&h=300&fit=crop',
              category: item.product.category?.name || 'Unknown Category',
              rating: item.product.rating || 4.5,
              isOnSale: item.product.isOnSale,
              discount: item.product.discount,
              stock: item.product.stock || 0
            },
            addedAt: new Date(item.addedAt)
          };
        });
        setWishlistItems(transformedItems);
      } else if (response.status === 404) {
        // Wishlist doesn't exist yet, use empty array
        setWishlistItems([]);
      } else {
        throw new Error('Failed to fetch wishlist');
      }
    } catch (error) {
      console.error('Error fetching wishlist:', error);
      // For demo purposes, use demo data if backend fails
      setWishlistItems(demoWishlistItems);
    } finally {
      setIsLoading(false);
    }
  };

  // Add item to wishlist
  const addToWishlist = async (product: any) => {
    if (!user || !token) {
      toast({
        title: "Authentication required",
        description: "Please log in to add items to wishlist",
        variant: "destructive",
      });
      return;
    }

    // Convert demo product ID to MongoDB ObjectId
    const realProductId = productIdMapping[product.id];
    if (!realProductId) {
      toast({
        title: "Error",
        description: "Product not found in database",
        variant: "destructive",
      });
      return;
    }

    try {
      setIsLoading(true);
      const response = await fetch(`${API_BASE_URL}/wishlist/add`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ productId: realProductId }),
      });

      if (response.ok) {
        const data = await response.json();
        
        // Check if data.data.items exists and is an array
        if (!data.data || !data.data.items || !Array.isArray(data.data.items)) {
          console.error('Invalid wishlist data structure:', data);
          throw new Error('Invalid wishlist data received from server');
        }
        
        // Transform backend data to frontend format
        const transformedItems = data.data.items.map((item: any) => {
          const reverseMapping = getReverseMapping();
          const frontendId = reverseMapping[item.product._id];

          return {
            id: item._id,
            product: {
              id: frontendId, // Use the frontend ID
              name: item.product.name,
              price: item.product.price,
              originalPrice: item.product.originalPrice,
              image: item.product.images?.[0]?.url || 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=300&h=300&fit=crop',
              category: item.product.category?.name || 'Unknown Category',
              rating: item.product.rating || 4.5,
              isOnSale: item.product.isOnSale,
              discount: item.product.discount,
              stock: item.product.stock || 0
            },
            addedAt: new Date(item.addedAt)
          };
        });
        
        setWishlistItems(transformedItems);
        toast({
          title: "Added to wishlist",
          description: `${product.name} has been added to your wishlist`,
        });
      } else {
        let errorData;
        try {
          errorData = await response.json();
        } catch (jsonError) {
          console.error('Failed to parse error response:', jsonError);
          errorData = { message: 'Unknown error occurred' };
        }
        
        console.log('Error response:', { status: response.status, data: errorData });
        
        // Handle the case where product is already in wishlist
        if (response.status === 400 && errorData.message && (
          errorData.message.includes('already in your wishlist') ||
          errorData.message.includes('Product is already in your wishlist')
        )) {
          toast({
            title: "Already in wishlist",
            description: "This item is already in your wishlist",
            variant: "default",
          });
          return;
        }
        
        throw new Error(errorData.message || 'Failed to add item to wishlist');
      }
    } catch (error) {
      console.error('Error adding to wishlist:', error);
      
      // Check if this is a 400 error about item already being in wishlist
      if (error instanceof Error && (
        error.message.includes('already in your wishlist') ||
        error.message.includes('Product is already in your wishlist')
      )) {
        toast({
          title: "Already in wishlist",
          description: "This item is already in your wishlist",
          variant: "default",
        });
        return;
      }
      
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to add item to wishlist",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Remove item from wishlist
  const removeFromWishlist = async (itemId: string) => {
    if (!user || !token) {
      toast({
        title: "Authentication required",
        description: "Please log in to manage wishlist",
        variant: "destructive",
      });
      return;
    }

    try {
      setIsLoading(true);
      const response = await fetch(`${API_BASE_URL}/wishlist/${itemId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const data = await response.json();
        
        // Check if data.data.items exists and is an array
        if (!data.data || !data.data.items || !Array.isArray(data.data.items)) {
          console.error('Invalid wishlist data structure:', data);
          throw new Error('Invalid wishlist data received from server');
        }
        
        // Transform backend data to frontend format
        const transformedItems = data.data.items.map((item: any) => {
          const reverseMapping = getReverseMapping();
          const frontendId = reverseMapping[item.product._id];

          return {
            id: item._id,
            product: {
              id: frontendId, // Use the frontend ID
              name: item.product.name,
              price: item.product.price,
              originalPrice: item.product.originalPrice,
              image: item.product.images?.[0]?.url || 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=300&h=300&fit=crop',
              category: item.product.category?.name || 'Unknown Category',
              rating: item.product.rating || 4.5,
              isOnSale: item.product.isOnSale,
              discount: item.product.discount,
              stock: item.product.stock || 0
            },
            addedAt: new Date(item.addedAt)
          };
        });
        
        setWishlistItems(transformedItems);
        toast({
          title: "Removed from wishlist",
          description: "Item has been removed from your wishlist",
        });
      } else {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to remove item from wishlist');
      }
    } catch (error) {
      console.error('Error removing from wishlist:', error);
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to remove item from wishlist",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Check if item is in wishlist
  const isInWishlist = (productId: number): boolean => {
    return wishlistItems.some(item => item.product.id === productId);
  };

  // Clear wishlist
  const clearWishlist = async () => {
    if (!user || !token) {
      toast({
        title: "Authentication required",
        description: "Please log in to manage wishlist",
        variant: "destructive",
      });
      return;
    }

    try {
      setIsLoading(true);
      const response = await fetch(`${API_BASE_URL}/wishlist/clear`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        setWishlistItems([]);
        toast({
          title: "Wishlist cleared",
          description: "All items have been removed from your wishlist",
        });
      } else {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to clear wishlist');
      }
    } catch (error) {
      console.error('Error clearing wishlist:', error);
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to clear wishlist",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Refresh wishlist
  const refreshWishlist = async () => {
    await fetchWishlist();
  };

  // Fetch wishlist when user changes
  useEffect(() => {
    fetchWishlist();
    // Only fetch product mapping if user is authenticated
    if (user && token) {
      fetchProductMapping(); // Fetch product mapping when component mounts
    }
  }, [user, token]);

  const value: WishlistContextType = {
    wishlistItems,
    isLoading,
    addToWishlist,
    removeFromWishlist,
    isInWishlist,
    clearWishlist,
    refreshWishlist,
  };

  return (
    <WishlistContext.Provider value={value}>
      {children}
    </WishlistContext.Provider>
  );
}; 